name: DocAI

on:
  push:
    branches: [master]

jobs:
  docai:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Scanner
        run: pip install git+https://github.com/ManojVihari/docai.git#subdirectory=scanner

      - name: Run DocAI
        run: docai-scan --commit HEAD --server https://1e9f-2401-4900-4e1f-a965-5cff-82d8-c021-cb70.ngrok-free.app
